### ISSUE TITLE
Tests are broken since 51a5ba57cc767d61e69fab87234f29d3c1e27008

### ISSUE THREAD

**Issue by Thaodan** [drmgc/i3ipcpp#41]
```
/usr/bin/c++ -DDEBUG=1 -DTEST_SRC_ROOT=\"/home/bidar/dev/kde/i3ipcpp/test\" -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/home/bidar/dev/kde/i3ipcpp/3rd/auss/include -I/home/bidar/dev/kde/i3ipcpp/include -I/home/bidar/dev/kde/i3ipcpp/include/i3ipc++ -std=c++11 -Wall -Wextra -Wno-unused-parameter -g3 -MD -MT CMakeFiles/i3ipcpp_check.dir/test.cpp.o -MF CMakeFiles/i3ipcpp_check.dir/test.cpp.o.d -o CMakeFiles/i3ipcpp_check.dir/test.cpp.o -c /home/bidar/dev/kde/i3ipcpp/build/test.cpp
In file included from /home/bidar/dev/kde/i3ipcpp/build/test.cpp:23:
/home/bidar/dev/kde/i3ipcpp/build/../test/test_ipc.hpp: In member function ‘void testsuite_ipc_util::test_pack()’:
/home/bidar/dev/kde/i3ipcpp/build/../test/test_ipc.hpp:17:57: error: ‘using std::__shared_ptr_access<i3ipc::buf_t, __gnu_cxx::_S_atomic, false, false>::element_type = struct i3ipc::buf_t’ {aka ‘struct i3ipc::buf_t’} has no member named ‘size’
   17 |                         for (uint32_t  i = 0; i < buff->size; i++) {
      |                                                         ^~~~
```
